[project]
name = "chat-app"
version = "0.1.0"
dependencies = [
    "fastapi>=0.104.0",
    "openai>=1.101.0",
    "uvicorn>=0.24.0",
]

[dependency-groups]
dev = [
    "deepeval>=3.4.1",
    "pytest>=8.4.1",
]
